### ISSUE TITLE
Error when app is Killed

### ISSUE THREAD

**Issue by gusilveiramp** [vikeri/react-native-background-job#102]
Hi guys,
If I run the app in Background, everything works, but if the app is Killed, I get an fatal error and everything shuts down. Can someone help me?

OS: Android
Version: 7.0
Device: Samsung Galaxy S7 (real device)
react: ^16.0.0
react-native: ^0.51.0
react-native-background-job: v2.2.0-beta

**build.gradle:**
compileSdkVersion 27
buildToolsVersion: '25.0.3'

defaultConfig {
...
    minSdkVersion 16
    targetSdkVersion 27
...
}

**adb Logcat:**
`
8-06 15:37:01.344  3727  3884 D SamsungAlarmManager: Expired : 8
08-06 15:37:01.345  3727  3884 V SamsungAlarmManager: Sending to uid : 10019 listener=android.os.BinderProxy@b4a9209 alarm=Alarm{6842d17 type 3 when 64313568 com.google.android.gms}
08-06 15:37:01.358  3727  5057 D SamsungAlarmManager: setExact Listener (T:3/F:1/AC:false) 20180806T160701 - CU:10019/CP:4918
08-06 15:37:01.364  4918 23239 W ctxmgr  : [AclManager]No 2 for (accnt=account#1707061657#, com.google.android.gms(10019):UserLocationProducer, vrsn=12874000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 4918). Was: 2 for 1, account#1707061657#
08-06 15:37:01.367  4918 23239 W ctxmgr  : [AclManager]No 2 for (accnt=account#-2003340818#, com.google.android.gms(10019):UserLocationProducer, vrsn=12874000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 4918). Was: 2 for 1, account#-2003340818#
08-06 15:37:02.148  3727  3884 D SamsungAlarmManager: Expired : 4
08-06 15:37:02.149  3727  3884 I SamsungAlarmManager: setLocked to kernel - T:2 / 20180806T153705, SetElapsed=64318163, nowELAPSED=64314373
08-06 15:37:02.150  3727  3884 V SamsungAlarmManager: Sending to uid : 10466 action=null alarm=Alarm{7cfed22 type 0 when 1533580622148 com.gtc.iokayapp}
08-06 15:37:02.157  3727  3884 D MountService: getExternalStorageMountMode : 3
08-06 15:37:02.157  3727  3884 D MountService: getExternalStorageMountMode : 3
08-06 15:37:02.157  3727  3884 D MountService: getExternalStorageMountMode : final mountMode=3, uid : 10466, packageName : com.gtc.iokayapp
08-06 15:37:02.193 25141 25141 E Zygote  : v2
08-06 15:37:02.193 25141 25141 I libpersona: KNOX_SDCARD checking this for 10466
08-06 15:37:02.193 25141 25141 I libpersona: KNOX_SDCARD not a persona
08-06 15:37:02.195 25141 25141 E Zygote  : accessInfo : 0
08-06 15:37:02.195  3727  3884 I ActivityManager: Start proc 25141:com.gtc.iokayapp/u0a466 for service com.gtc.iokayapp/com.pilloxa.backgroundjob.ExactJob
08-06 15:37:02.206 25141 25141 W SELinux : SELinux selinux_android_compute_policy_index : Policy Index[1],  Con:u:r:zygote:s0 SPD:SEPF_SECMOBILE_7.0_0006 RAM:SEPF_SECMOBILE_7.0_0005, [-1 -1 0 1 0 1]
08-06 15:37:02.208 25141 25141 I SELinux : SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.gtc.iokayapp
08-06 15:37:02.214 25141 25141 I art     : Late-enabling -Xcheck:jni
08-06 15:37:02.250 25141 25141 D TimaKeyStoreProvider: TimaSignature is unavailable
08-06 15:37:02.251 25141 25141 D ActivityThread: Added TimaKeyStore provider
08-06 15:37:02.257  3727  3957 I ActivityManager: DSS on for com.gtc.iokayapp and scale is 1.0
08-06 15:37:02.348 25141 25141 D ContextRelationMgrBrdg: loadKlass() : caller=com.samsung.android.bridge.multiscreen.common.ContextRelationManagerBridge.<clinit>:28 android.app.LoadedApk.makeApplication:840
08-06 15:37:02.370 25141 25141 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
08-06 15:37:02.385 25141 25141 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
08-06 15:37:02.397 25141 25141 I FirebaseInitProvider: FirebaseApp initialization successful
08-06 15:37:02.403  3727  5056 D SamsungAlarmManager: Cancel Alarm calling from uid:10466 pid :25141 / op:PendingIntent{4ecd70: PendingIntentRecord{8c5c8e9 com.gtc.iokayapp broadcastIntent}}
08-06 15:37:02.411 25141 25159 D ReactNativeEventStarter: trigger() called with: jobBundle = [Bundle[{networkType=-1, allowWhileIdle=true, timeout=2000, jobKey=myJob, period=3000, persist=true, android.intent.extra.ALARM_TARGET_TIME=1533580616059, allowExecutionInForeground=false, override=true, android.intent.extra.ALARM_COUNT=1, requiresCharging=false, requiresDeviceIdle=false}]]
08-06 15:37:02.421 25141 25159 D MyHeadlessJsTaskService: start() called with: context = [com.pilloxa.backgroundjob.ExactJob@c6278ac], jobBundle = [Bundle[{networkType=-1, allowWhileIdle=true, timeout=2000, jobKey=myJob, period=3000, persist=true, android.intent.extra.ALARM_TARGET_TIME=1533580616059, allowExecutionInForeground=false, override=true, android.intent.extra.ALARM_COUNT=1, requiresCharging=false, requiresDeviceIdle=false}]]
**08-06 15:37:02.441 25141 25141 D MyHeadlessJsTaskService: getTaskConfig() called with: intent = [Intent { cmp=com.gtc.iokayapp/com.pilloxa.backgroundjob.ReactNativeEventStarter$MyHeadlessJsTaskService launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }]
08-06 15:37:02.443 25141 25141 D AndroidRuntime: Shutting down VM
08-06 15:37:02.445 25141 25141 E AndroidRuntime: FATAL EXCEPTION: main
08-06 15:37:02.445 25141 25141 E AndroidRuntime: Process: com.gtc.iokayapp, PID: 25141
08-06 15:37:02.445 25141 25141 E AndroidRuntime: java.lang.ExceptionInInitializerError
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.facebook.react.bridge.Arguments.createMap(Arguments.java:165)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:289)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.pilloxa.backgroundjob.ReactNativeEventStarter$MyHeadlessJsTaskService.getTaskConfig(ReactNativeEventStarter.java:78)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.facebook.react.HeadlessJsTaskService.onStartCommand(HeadlessJsTaskService.java:51)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3685)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at android.app.ActivityThread.-wrap23(ActivityThread.java)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1740)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6692)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
08-06 15:37:02.445 25141 25141 E AndroidRuntime: Caused by: java.lang.RuntimeException: SoLoader.init() not yet called
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.facebook.soloader.SoLoader.assertInitialized(SoLoader.java:335)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:238)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:20)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:21)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        ... 13 more**
08-06 15:37:02.449  3727  9871 D Debug   : !@DumpState : SHIP
08-06 15:37:02.449  3727  9871 D Debug   : !@DumpState : debug level:0x4f4c
08-06 15:37:02.449  3727  9871 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
08-06 15:37:02.456  3727 25162 W DropBoxManagerService: Dropping: data_app_crash (1502 > 0 bytes)
08-06 15:37:02.456  3727  8739 D SamsungAlarmManager: setExact Intent (T:0/F:5/AC:false) 20180806T153705 - CU:10466/CP:25141
08-06 15:37:02.456  3727  8739 I SamsungAlarmManager: setLocked to kernel - T:2 / 20180806T153705, SetElapsed=64317655, nowELAPSED=64314680
08-06 15:37:02.459 25141 25158 I FA      : App measurement is starting up, version: 12211
08-06 15:37:02.459 25141 25158 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
08-06 15:37:02.459 25141 25158 I FA      : To enable faster debug mode event logging run:
08-06 15:37:02.459 25141 25158 I FA      :   adb shell setprop debug.firebase.analytics.app com.gtc.iokayapp
08-06 15:37:02.508 21747 21747 I DMT-DropBoxReceiver: Received : android.intent.action.DROPBOX_ENTRY_ADDED
08-06 15:37:02.509 21747 21747 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1386 android.content.ContextWrapper.startService:656 android.content.ContextWrapper.startService:656 com.samsung.android.sm.common.DropBoxReceiver.a:47 com.samsung.android.sm.common.DropBoxReceiver.onReceive:29
08-06 15:37:02.524  3727  3787 D WindowManager: addWindow: android.view.ViewRootImpl$W@4aad58a displayId=0
08-06 15:37:02.525  3727  3787 D InputTransport: Input channel constructed: fd=401
08-06 15:37:02.525  3727  3787 D InputTransport: Input channel constructed: fd=485
08-06 15:37:02.526  3727  3787 V MARsPolicyManager: handelAlertToastWindowStarted pkgName = android
08-06 15:37:02.527  3727  3787 D InputDispatcher: Focus left window: 5160
08-06 15:37:02.527  3727  3787 D InputDispatcher: Focus entered window: 3727
08-06 15:37:02.528  3727  3787 D ViewRootImpl@29d93f5[iokayapp]: setView = DecorView@3848d7[iokayapp] touchMode=true
08-06 15:37:02.547  3727  3787 V WindowManager: Relayout Window{c8927fbd0 u0 Application Error: com.gtc.iokayapp}: viewVisibility=0 req=1015x442 WM.LayoutParams{(0,0)(wrapxwrap) gr=#11 sim=#120 ty=2003 fl=#1820002 pfl=0x110 fmt=-3 wanim=0x103038b surfaceInsets=Rect(6, 6 - 6, 6) needsMenuKey=2 naviIconColor=0}
08-06 15:37:02.548  3113  3113 I SurfaceFlinger: id=989 createSurf (13x13),1 flag=4, jokayapp
08-06 15:37:02.568 21747 25169 V CrashedAppLogging: isMasterSwitchOff : false
08-06 15:37:02.578  3727  4050 I OpenGLRenderer: Initialized EGL, version 1.4
08-06 15:37:02.578  3727  4050 D OpenGLRenderer: Swap behavior 1
08-06 15:37:02.592  3727  3787 D WindowManager: set systemUiVisibility of statusbar : vis= 0x8
08-06 15:37:02.595  3727  3787 D ViewRootImpl@29d93f5[iokayapp]: MSG_WINDOW_FOCUS_CHANGED 1
08-06 15:37:02.598  3727  5105 D WindowManager: adjustSystemUiVisibilityLw : vis= 0x8
08-06 15:37:02.599  3727  4050 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1027x454]-format:1
08-06 15:37:02.633  3727  3787 D WindowManager: finishDrawingWindow: Window{c8927fbd0 u0 Application Error: com.gtc.iokayapp} mDrawState=DRAW_PENDING
08-06 15:37:02.634  3727  3787 D ViewRootImpl@29d93f5[iokayapp]: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
08-06 15:37:02.644  5160  5160 D ViewRootImpl@d57a710[LauncherActivity]: MSG_WINDOW_FOCUS_CHANGED 0
08-06 15:37:02.645  3727  3787 D WindowManager: finishDrawingWindow: Window{c8927fbd0 u0 Application Error: com.gtc.iokayapp} mDrawState=HAS_DRAWN
08-06 15:37:03.398  4740  4740 D io_stats: !@   8,0 r 425755 16117280 w 275697 4758492 d 30629 1680532 f 81201 81185 iot 315120 255456 th 435876 0 0 pt 0 inp 0 0 31845.210
`

The error: 
**08-06 15:37:02.441 25141 25141 D MyHeadlessJsTaskService: getTaskConfig() called with: intent = [Intent { cmp=com.gtc.iokayapp/com.pilloxa.backgroundjob.ReactNativeEventStarter$MyHeadlessJsTaskService launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }]
08-06 15:37:02.443 25141 25141 D AndroidRuntime: Shutting down VM
08-06 15:37:02.445 25141 25141 E AndroidRuntime: FATAL EXCEPTION: main
08-06 15:37:02.445 25141 25141 E AndroidRuntime: Process: com.gtc.iokayapp, PID: 25141
08-06 15:37:02.445 25141 25141 E AndroidRuntime: java.lang.ExceptionInInitializerError
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.facebook.react.bridge.Arguments.createMap(Arguments.java:165)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.facebook.react.bridge.Arguments.fromBundle(Arguments.java:289)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.pilloxa.backgroundjob.ReactNativeEventStarter$MyHeadlessJsTaskService.getTaskConfig(ReactNativeEventStarter.java:78)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.facebook.react.HeadlessJsTaskService.onStartCommand(HeadlessJsTaskService.java:51)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3685)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at android.app.ActivityThread.-wrap23(ActivityThread.java)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1740)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6692)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
08-06 15:37:02.445 25141 25141 E AndroidRuntime: Caused by: java.lang.RuntimeException: SoLoader.init() not yet called
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.facebook.soloader.SoLoader.assertInitialized(SoLoader.java:335)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:238)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:20)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:21)
08-06 15:37:02.445 25141 25141 E AndroidRuntime:        ... 13 more**

**Comment by vikeri** [comment]
Does the example project work for you?
