### ISSUE TITLE
failed to find Build Tools revision 25.0.0

### ISSUE THREAD

**Issue by creativefull** [vikeri/react-native-background-job#22]
why i must be update my build too revision ?
my project already use with build tools revision 23

i get error like this
```
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: failed to find Build Tools revision 25.0.0
	at com.android.builder.sdk.DefaultSdkLoader.getTargetInfo(DefaultSdkLoader.java:93)
	at com.android.build.gradle.internal.SdkHandler.initTarget(SdkHandler.java:89)
	at com.android.build.gradle.BasePlugin.ensureTargetSetup(BasePlugin.groovy:507)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.groovy:455)
	at com.android.build.gradle.BasePlugin$_createTasks_closure13_closure17.doCall(BasePlugin.groovy:415)
	at com.android.build.gradle.BasePlugin$_createTasks_closure13_closure17.doCall(BasePlugin.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at com.android.build.gradle.internal.profile.SpanRecorders$2.call(SpanRecorders.groovy:52)
	at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMet
```

thanks :)

**Comment by vikeri** [comment]
You don't have to upgrade your build tools in your project, but you have to download `25.0.0` in Android SDK manager: https://developer.android.com/studio/intro/update.html#sdk-manager

**Comment by creativefull** [comment]
already fix upgrade build tool in my project, but not run in android < 5

**Comment by vikeri** [comment]
No activity for a long time. Closing. Please create new issue if re-encountered.
